baseurl = "https://bitarchivist.net/"
languageCode = "en-US"
title = "Tim Walsh - Digital archivist, coder"
disqusShortname = ""
googleAnalytics = "UA-97498540-1"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Tim Walsh"
  description = "I'm an archivist who spends a lot of time thinking about digital preservation, the web, and possibilities for access afforded by born-digital objects. Let's build an accessible bridge to the past together."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "timothyryanwalsh"
  Email         = "timothyryanwalsh@gmail.com"
  Twitter       = "bitarchivist"
  LinkedIn      = "timothyryanwalsh/"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "cv"
  identifier = "cv"
  weight = 200
  url = "/cv/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 300
  url = "/projects/"